load NUMBER_OF_ELEMENTS.TXT
load NUMBER_OF_PHASES.TXT
load DIMENSIONALITY.TXT
load NUMBER_OF_GRID_POINTS.TXT
load DOMAIN_SIZE.TXT
load FINITE_VOLUME_CENTROID_COORDINATES.TXT
load MOLE_FRACTIONS.TXT
load CHEMICAL_POTENTIALS.TXT
load TIME.TXT

nel=NUMBER_OF_ELEMENTS;
nph=NUMBER_OF_PHASES;
ngp=NUMBER_OF_GRID_POINTS;
domain_size=DOMAIN_SIZE;

